In [1]:
import requests
import numpy as np
import pandas as pd
import herepy
import config
import json
import isodate
from datetime import datetime as dt

In [5]:
residents = pd.read_csv("addresses_simulated_incomes_pitt.csv")
pittsburgh_mask = residents['MUNICIPALITY']=='PITTSBURGH'
pittsburgh = residents[pittsburgh_mask]
car_mask = pittsburgh['simulated_commute_car']==1
residents_car = pittsburgh[car_mask]
residents_transit = pittsburgh[-car_mask]
#Need to add store and vacant lot locations into a single df. Idk where current store info is--can you add that and the
#vacant lot data here?
lots = pd.read_csv("vacant_lots_centroid.csv")
stores = pd.read_csv("supermarkets.csv")

OBJECTID                    Company_Name              Address        City  \
0          1          5th Avenue Food Market         1701 5th Ave  Pittsburgh   
1          2                     Aden Market  1318 Federal St # 1  Pittsburgh   
2          3                            ALDI     2628 E Carson St  Pittsburgh   
3          4                            ALDI        5200 Penn Ave  Pittsburgh   
4          5                            ALDI       5631 Baum Blvd  Pittsburgh   
..       ...                             ...                  ...         ...   
56        72                   W N Grocery's     1018 W North Ave  Pittsburgh   
57        73              Whole Foods Market      5880 Centre Ave  Pittsburgh   
58        74              Wild Purveyors LLC   5308 Butler St # A  Pittsburgh   
59        75           Yi Chung Kwan Grocery         4701 5th Ave  Pittsburgh   
60        76  Young's Oriental Grocery Store     5813 Forward Ave  Pittsburgh   

   State  ZIP_Code  NAICS_1  \
0     PA     15219   445110   
1     PA     15212   445110   
2     PA     15203   445110   
3     PA     15224   445110   
4     PA     15206   445110   
..   ...       ...      ...   
56    PA     15233   445110   
57    PA     15206   445110   
58    PA     15201   445110   
59    PA     15213   445110   
60    PA     15217   445110   

                                  NAICS_1_Description   Latitude  Longitude  \
0   Supermarkets/Other Grocery (Exc Convenience) Strs  40.438553 -79.982357   
1   Supermarkets/Other Grocery (Exc Convenience) Strs  40.457247 -80.006974   
2   Supermarkets/Other Grocery (Exc Convenience) Strs  40.426989 -79.967410   
3   Supermarkets/Other Grocery (Exc Convenience) Strs  40.464217 -79.939334   
4   Supermarkets/Other Grocery (Exc Convenience) Strs  40.467565 -79.922069   
..                                                ...        ...        ...   
56  Supermarkets/Other Grocery (Exc Convenience) Strs  40.453283 -80.020292   
57  Supermarkets/Other Grocery (Exc Convenience) Strs  40.458567 -79.928698   
58  Supermarkets/Other Grocery (Exc Convenience) Strs  40.482271 -79.952199   
59  Supermarkets/Other Grocery (Exc Convenience) Strs  40.447235 -79.947104   
60  Supermarkets/Other Grocery (Exc Convenience) Strs  40.429616 -79.922707   

    price score  
0             2  
1             2  
2             1  
3             1  
4             1  
..          ...  
56            1  
57            3  
58            3  
59            2  
60            1  

[61 rows x 11 columns]

In [13]:
#limited rows for testing. Change to residents_car.loc[:, [..]].values instead of the slices to use whole datasets
start_car_coords = residents_car.loc[:,["LATITUDE", "LONGITUDE"]].values
start_transit_coords = residents_transit.loc[:,["LATITUDE", "LONGITUDE"]].values
end_coords_lots = lots.loc[:,["Y", "X"]].values
end_coords_stores = stores.loc[:,["Latitude","Longitude"]].values
end_coords = np.concatenate((end_coords_lots,end_coords_stores),axis=0)

routingApi = herepy.RoutingApi(config.api_key)
publicTransitApi = herepy.PublicTransitApi(config.api_key)

In [14]:
# create blank lists that will be populated with trip characteristics
car_origin= []
car_destination= []
car_trip_miles= []
car_trip_time= []

#use car_api_start and car_api_end to time how long the API takes to run
car_api_start = dt.now()

#api is breaking without indicating the problematic row, so need to for loop it and wrap in try except
for i in range(0,len(start_car_coords)):
    for j in range(0,len(end_coords)):
        car_origin.append(i)
        car_destination.append(j)
        try:
            response_car = routingApi.matrix(
                    start_waypoints=start_car_coords[i:(i+1)],
                    destination_waypoints=end_coords[j:(j+1)],
                    departure='2020-08-04T17:00:00+02',
                    summary_attributes = ['traveltime','distance'],
                    modes=[herepy.RouteMode.fastest, herepy.RouteMode.car])
            #extract trip from response
            trip = response_car.as_dict()['response']['matrixEntry'][0]
            # store values
            car_trip_miles.append(trip['summary']['distance']/1609.34)
            car_trip_time.append(trip['summary']['travelTime']/3600)
        except:
            car_trip_miles.append(9999999)
            car_trip_time.append(999999999)


car_api_end = dt.now()


In [15]:

car_results = pd.DataFrame({"origin":car_origin,
              "destination":car_destination,
              "trip_distance":car_trip_miles,
              "trip_time":car_trip_time})
car_results['travel_cost'] = (car_results['trip_distance']*.575) + car_results['trip_time']*7.5

#store costs in i by k matrix
car_time_mat = car_results.pivot(index='origin',columns='destination',values='trip_time')
car_cost_mat = car_results.pivot(index='origin',columns='destination',values='travel_cost')

car_time_mat

destination       0         1         2         3         4         5    \
origin                                                                    
0            0.546389  0.297500  0.246667  0.434167  0.443611  0.330833   
1            0.392500  0.269444  0.256667  0.352778  0.289722  0.302222   
2            0.347778  0.376111  0.402500  0.056389  0.140833  0.408889   
3            0.254167  0.355000  0.381389  0.154722  0.034722  0.387778   
4            0.483611  0.249444  0.268056  0.299167  0.308611  0.282222   
...               ...       ...       ...       ...       ...       ...   
430          0.549167  0.367500  0.342500  0.488889  0.452778  0.421389   
431          0.452222  0.307778  0.334167  0.188056  0.266944  0.340556   
432          0.415833  0.324722  0.351111  0.130000  0.208889  0.357500   
433          0.409444  0.271389  0.297778  0.218611  0.228056  0.304167   
434          0.418056  0.274444  0.300833  0.223056  0.236667  0.307222   

destination       6         7         8         9    ...       303       304  \
origin                                               ...                       
0            0.577222  0.333056  0.237500  0.350000  ...  0.350000  0.397222   
1            0.423333  0.251667  0.208889  0.292500  ...  0.319444  0.319167   
2            0.378611  0.123889  0.315556  0.397500  ...  0.196389  0.154444   
3            0.285000  0.119722  0.294444  0.290278  ...  0.280000  0.051944   
4            0.514444  0.198056  0.188889  0.289722  ...  0.198333  0.262222   
...               ...       ...       ...       ...  ...       ...       ...   
430          0.581111  0.387778  0.328056  0.261667  ...  0.440556  0.451944   
431          0.483056  0.139444  0.247222  0.327500  ...  0.098056  0.214167   
432          0.446667  0.109722  0.264167  0.346111  ...  0.136944  0.156111   
433          0.440278  0.117500  0.210833  0.291111  ...  0.113611  0.181667   
434          0.448889  0.107778  0.213889  0.295833  ...  0.189167  0.190278   

destination       305       306       307       308       309       310  \
origin                                                                    
0            0.212778  0.195000  0.330000  0.269722  0.191944  0.016944   
1            0.169722  0.199722  0.329722  0.279722  0.167778  0.214167   
2            0.436389  0.466389  0.359722  0.321111  0.434444  0.424167   
3            0.371111  0.402222  0.338611  0.300000  0.396944  0.403056   
4            0.363333  0.386944  0.083611  0.144444  0.373056  0.300833   
...               ...       ...       ...       ...       ...       ...   
430          0.127222  0.096944  0.420556  0.360278  0.094722  0.147778   
431          0.368889  0.398889  0.288611  0.236389  0.366944  0.356667   
432          0.385000  0.415000  0.316944  0.278333  0.383056  0.372778   
433          0.334722  0.364722  0.234444  0.195833  0.332778  0.322500   
434          0.334722  0.364722  0.266667  0.228056  0.332778  0.322500   

destination       311       312  
origin                           
0            0.233889  0.328056  
1            0.103333  0.244722  
2            0.391667  0.352500  
3            0.290278  0.245278  
4            0.283889  0.244722  
...               ...       ...  
430          0.190833  0.243056  
431          0.321667  0.282500  
432          0.340278  0.301111  
433          0.285278  0.246111  
434          0.290000  0.250833  

[435 rows x 313 columns]

In [16]:
#it took 8 and a half minutes to run 50 starts by 100 destinations, doing the starts in batches of 15
#should speed things up
(car_api_end-car_api_start).seconds/60

242.58333333333334

In [27]:
#try to use the public transit api for transit starting points, and if it fails
#because there is no public transit stop nearby, use walking directions
#create a blank list to store transit_times
transit_origins = []
transit_destinations = []
transit_times = []
transit_api_start = dt.now()
transit_fares = []
for i in range(0,len(start_transit_coords)):
    if i%20==0:
        print(i)
    for j in range(0,len(end_coords)):
        transit_origins.append(i)
        transit_destinations.append(j)
        try:
            response_transit = publicTransitApi.calculate_route(
                departure = list(start_transit_coords[i]),
                arrival = list(end_coords[j]),
                time = '2020-08-04T17:00:00+02')
            #extract trip_time from response
            trip_time = response_transit.as_dict()['Res']['Connections']['Connection'][0]['duration']
            # store trip time in hours
            transit_times.append(isodate.parse_duration(trip_time).seconds/3600)
            #add fare of 3.5
            transit_fares.append(3.5)
        except:
            response_ped = routingApi.matrix(
                start_waypoints=list(start_transit_coords[i:(i+1)]),
                destination_waypoints=list(end_coords[j:(j+1)]),
                departure='2020-08-04T17:00:00+02',
                summary_attributes = ['traveltime','distance'],
                modes=[herepy.RouteMode.fastest, herepy.RouteMode.pedestrian])
            
            trip = response_ped.as_dict()['response']['matrixEntry'][0]
            # if the call fails, it'll return a "status" in the response, to test for that
            if( 'status' in trip.keys()):
                #impute a very large trip time so 
                trip_time = 99999999999
            else: 
                trip_time = trip['summary']['travelTime']
            
            transit_times.append(trip_time/3600)
            #fare is 0 since they're walking
            transit_fares.append(0)
#timestamp
transit_api_end = dt.now()
#store results in tall dataframe
transit_results = pd.DataFrame({"origin":transit_origins,
                                "destination":transit_destinations,
                                "trip_time":transit_times,
                                "transit_fares":transit_fares})
#calculate trip cost using formula in paper
transit_results['trip_costs'] = (transit_results['trip_time']*7.5)+transit_results['transit_fares']

#store times and costs as i x k matrix
transit_time_mat = transit_results.pivot(index='origin',columns='destination',values='trip_time')
transit_cost_mat = transit_results.pivot(index='origin',columns='destination',values='trip_costs')

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280


In [30]:
transit_api_end-transit_api_start

datetime.timedelta(seconds=25174, microseconds=160584)

In [28]:
#combine time matrix and cost matrix
time_mat = pd.concat([car_time_mat,transit_time_mat])
#reset the row numbers
time_mat.reset_index(inplace=True)

cost_mat = pd.concat([car_cost_mat,transit_cost_mat])
cost_mat.reset_index(inplace=True)

#also combine the two household location matrices, which should now be the same number of rows
pittsburgh=pd.concat([residents_car,residents_transit])
pittsburgh.reset_index(inplace=True)


In [31]:
#save csvs of each
time_mat.to_csv('data/travel_times_all.csv')
cost_mat.to_csv('data/travel_costs_all.csv')
pittsburgh.to_csv('data/pittsburgh_all.csv')

Index(['origin',        0,        1,        2,        3,        4,        5,
              6,        7,        8,
       ...
            303,      304,      305,      306,      307,      308,      309,
            310,      311,      312],
      dtype='object', name='destination', length=314)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

0.7442

25

array([[ 40.4550461, -80.0528284],
       [ 40.4695965, -79.9169844]])

[40.455046100000004, -80.05282840000001]

array([[ 40.4550461, -80.0528284],
       [ 40.4695965, -79.9169844]])

destination         0         1         2         3         4
origin                                                       
0            0.283889  0.330833  0.357222  0.141389  0.068611
1            0.611667  0.340278  0.298611  0.486111  0.495556
2            0.823611  0.552222  0.510556  0.698056  0.714444
3            0.831111  0.559722  0.518056  0.705556  0.721944
4            0.852500  0.581111  0.539444  0.726944  0.743333

In [70]:
residents_transit

GEOID               FULL_ADDRESS               MUNICIPALITY  \
4    42003562500            2913 ZEPHYR AVE                 PITTSBURGH   
5    42003110600            822 COLLINS AVE                 PITTSBURGH   
7    42003040500           258 1/2 MCKEE PL                 PITTSBURGH   
8    42003480200          1636 ELDERSLEE RD            BALDWIN BOROUGH   
21   42003563000            1105 VILLAGE RD                 PITTSBURGH   
22   42003110600            6316 JACKSON ST                 PITTSBURGH   
25   42003479000              571 DEWALT DR           BALDWIN TOWNSHIP   
26   42003488600             321 GLENCOE DR       WEST MIFFLIN BOROUGH   
28   42003562400            226 CHALFONT ST                 PITTSBURGH   
29   42003492800            540 HALCOMB AVE                   CLAIRTON   
34   42003551900                318 5TH AVE                 MCKEESPORT   
42   42003130100            1518 N LANG AVE                 PITTSBURGH   
64   42003507000               452 LONG AVE  NORTH VERSAILLES TOWNSHIP   
66   42003281500              132 ELMONT ST                 PITTSBURGH   
71   42003475401              5725 JANET DR   BETHEL PARK MUNICIPALITY   
76   42003465600               21 WHITE AVE            CRAFTON BOROUGH   
80   42003151600              4117 LYDIA ST                 PITTSBURGH   
81   42003020100                2 MARKET SQ                 PITTSBURGH   
88   42003473100            304 KENMONT AVE              MOUNT LEBANON   
96   42003426700        1044 SAXONBURG BLVD            SHALER TOWNSHIP   
97   42003424000              122 N MAIN ST         SHARPSBURG BOROUGH   
100  42003461000  6900 RIVERSIDE PL BLDG 35           NEVILLE TOWNSHIP   
102  42003481000               322 ONYX AVE       MOUNT OLIVER BOROUGH   
105  42003470400             1624 NORSEN DR             SCOTT TOWNSHIP   
107  42003290200             1702 LEOLYN ST                 PITTSBURGH   
108  42003551200           2901 FREELAND ST                 MCKEESPORT   
110  42003101600            4710 KINCAID ST                 PITTSBURGH   
112  42003270400             1123 INGHAM ST                 PITTSBURGH   
122  42003270300         3547 SHADELAND AVE                 PITTSBURGH   
125  42003484300              1046 CREEK ST            MUNHALL BOROUGH   
..           ...                        ...                        ...   
598  42003564400           1210 DENNING WAY  NORTH VERSAILLES TOWNSHIP   
599  42003481000             332 ANTHONY ST       MOUNT OLIVER BOROUGH   
605  42003080200        4701 1/2 LORIGAN ST                 PITTSBURGH   
606  42003507000        924 PUNTA GORDA AVE    EAST MCKEESPORT BOROUGH   
609  42003020100              550 MARKET ST                 PITTSBURGH   
613  42003474202      2351 HIDDEN TIMBER DR    UPPER ST CLAIR TOWNSHIP   
617  42003409000          124 NORTHBROOK DR              PINE TOWNSHIP   
618  42003521500        134 COLLEGE PARK DR   MONROEVILLE MUNICIPALITY   
622  42003551900               505 SHAW AVE                 MCKEESPORT   
623  42003060300              3417 DENNY ST                 PITTSBURGH   
626  42003470600                618 HOPE ST             SCOTT TOWNSHIP   
631  42003070300                 912 IVY ST                 PITTSBURGH   
634  42003070900             5445 POTTER ST                 PITTSBURGH   
635  42003521401      434 ALPINE VILLAGE DR   MONROEVILLE MUNICIPALITY   
636  42003151600              338 SALINE ST                 PITTSBURGH   
637  42003562400            137 MICHIGAN ST                 PITTSBURGH   
640  42003451105            9306 LANDING LN              MOON TOWNSHIP   
644  42003210700           1434 W NORTH AVE                 PITTSBURGH   
646  42003271500      2707 1/2 FREDERICK ST                 PITTSBURGH   
658  42003310200           4921 LOUGEAN AVE                 PITTSBURGH   
659  42003430200             58 FORDHAM AVE          WEST VIEW BOROUGH   
660  42003090200                306 MAIN ST                 PITTSBURGH   
663  4200350300

In [74]:
start_transit_coords

array([[ 40.4550461, -80.0528284],
       [ 40.4695965, -79.9169844]])

In [225]:
test = isodate.parse_duration(response_transit.as_dict()['Res']['Connections']['Connection'][0]['duration'])
test.seconds

5940

In [129]:
len(start_transit_coords)

166

In [154]:
trip_list[0]

{'startIndex': 0,
 'destinationIndex': 0,
 'summary': {'distance': 8918, 'travelTime': 1022, 'costFactor': 1042}}